CREATE TABLE "bank_accounts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"account_holder_name" text NOT NULL,
	"account_number" text NOT NULL,
	"ifsc_code" text NOT NULL,
	"bank_name" text,
	"upi_id" text,
	"razorpay_contact_id" text,
	"razorpay_fund_account_id" text,
	"verified" text DEFAULT 'pending',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "bank_accounts_partner_id_unique" UNIQUE("partner_id")
);
--> statement-breakpoint
CREATE TABLE "bank_loan_approvals" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar,
	"bank_loan_submission_id" varchar,
	"customer_name" text NOT NULL,
	"bank_name" text NOT NULL,
	"bank_branch" text,
	"approval_date" timestamp NOT NULL,
	"approval_time" text,
	"approved_amount" numeric(12, 2),
	"interest_rate" numeric(5, 2),
	"loan_tenure" integer,
	"status" text DEFAULT 'approved',
	"remarks" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "bank_loan_submissions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"bank_name" text NOT NULL,
	"bank_branch" text NOT NULL,
	"bank_manager_name" text,
	"bank_manager_mobile" text,
	"submission_date" timestamp NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"loan_amount" numeric(12, 2),
	"remarks" text,
	"created_by" varchar NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "chatbot_faq" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"question" text NOT NULL,
	"answer" text NOT NULL,
	"category" text NOT NULL,
	"keywords" text[],
	"is_active" text DEFAULT 'active',
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "commissions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"partner_type" text DEFAULT 'ddp' NOT NULL,
	"customer_id" varchar,
	"source" text DEFAULT 'installation' NOT NULL,
	"capacity_kw" integer NOT NULL,
	"commission_amount" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"paid_at" timestamp,
	"notes" text,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "customer_file_submissions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar,
	"customer_name" text NOT NULL,
	"consumer_no" text NOT NULL,
	"bill_holder_name" text NOT NULL,
	"loan_applied" boolean DEFAULT false,
	"submission_date" timestamp NOT NULL,
	"status" text DEFAULT 'submitted',
	"remarks" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "customer_sessions" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"session_token" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "customer_sessions_session_token_unique" UNIQUE("session_token")
);
--> statement-breakpoint
CREATE TABLE "customer_testimonials" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"customer_name" text NOT NULL,
	"customer_district" text,
	"customer_state" text,
	"installed_capacity" text,
	"testimonial_text" text,
	"rating" integer,
	"video_url" text,
	"video_thumbnail" text,
	"video_duration" integer,
	"plant_photos" text[],
	"shared_on_facebook" boolean DEFAULT false,
	"shared_on_instagram" boolean DEFAULT false,
	"facebook_share_date" timestamp,
	"instagram_share_date" timestamp,
	"status" text DEFAULT 'pending' NOT NULL,
	"approved_by" varchar,
	"approved_at" timestamp,
	"is_featured" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "customer_vendor_assignments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"vendor_id" varchar NOT NULL,
	"job_role" text NOT NULL,
	"journey_stage" text DEFAULT 'installation' NOT NULL,
	"scheduled_date" timestamp,
	"completed_date" timestamp,
	"status" text DEFAULT 'pending' NOT NULL,
	"notes" text,
	"amount_quoted" numeric(12, 2),
	"amount_paid" numeric(12, 2),
	"invoice_number" text,
	"assigned_by" varchar,
	"assigned_at" timestamp DEFAULT now(),
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"email" text,
	"phone" text NOT NULL,
	"address" text NOT NULL,
	"district" text NOT NULL,
	"state" text NOT NULL,
	"pincode" text NOT NULL,
	"electricity_board" text,
	"consumer_number" text,
	"sanctioned_load" text,
	"avg_monthly_bill" integer,
	"roof_type" text,
	"roof_area" integer,
	"panel_type" text DEFAULT 'dcr',
	"proposed_capacity" text,
	"customer_type" text DEFAULT 'residential',
	"status" text DEFAULT 'pending' NOT NULL,
	"ddp_id" varchar NOT NULL,
	"documents" text[],
	"account_holder_name" text,
	"account_number" text,
	"ifsc_code" text,
	"bank_name" text,
	"upi_id" text,
	"latitude" text,
	"longitude" text,
	"installation_date" timestamp,
	"site_pictures" text[],
	"site_video" text,
	"lead_score" integer,
	"lead_score_details" text,
	"lead_score_updated_at" timestamp,
	"source" text,
	"referrer_customer_id" varchar,
	"portal_enabled" boolean DEFAULT false,
	"portal_access_code" text,
	"password_hash" text,
	"password_set_at" timestamp,
	"otp_code" text,
	"otp_expiry" timestamp,
	"last_portal_login" timestamp,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"original_name" text NOT NULL,
	"category" text NOT NULL,
	"mime_type" text NOT NULL,
	"size" integer NOT NULL,
	"url" text NOT NULL,
	"customer_id" varchar,
	"partner_id" varchar,
	"uploaded_by_id" varchar NOT NULL,
	"uploaded_by_role" text NOT NULL,
	"description" text,
	"is_verified" boolean DEFAULT false,
	"verified_by_id" varchar,
	"verified_at" timestamp,
	"expires_at" timestamp,
	"tags" text[],
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "feedback" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar,
	"user_email" text,
	"user_name" text,
	"type" text DEFAULT 'suggestion' NOT NULL,
	"subject" text NOT NULL,
	"message" text NOT NULL,
	"priority" text DEFAULT 'medium',
	"status" text DEFAULT 'pending' NOT NULL,
	"page" text,
	"admin_notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "goods_deliveries" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar,
	"purchase_order_id" varchar,
	"vendor_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"delivery_address" text NOT NULL,
	"district" text,
	"state" text,
	"pincode" text,
	"scheduled_date" timestamp NOT NULL,
	"scheduled_time_slot" text,
	"actual_delivery_date" timestamp,
	"status" text DEFAULT 'scheduled',
	"delivered_by" text,
	"vehicle_number" text,
	"vehicle_type" text,
	"panel_type" text,
	"panel_capacity" text,
	"inverter_type" text,
	"quantity_ordered" integer DEFAULT 1,
	"quantity_delivered" integer,
	"logistic_rate" numeric(10, 2) DEFAULT '20',
	"delivery_distance_km" numeric(10, 2),
	"receiver_name" text,
	"receiver_phone" text,
	"receiver_signature" text,
	"delivery_photos" text[],
	"site_verification_before" text[],
	"site_verification_after" text[],
	"verification_notes" text,
	"po_number" text,
	"vendor_name" text,
	"remarks" text,
	"failure_reason" text,
	"reschedule_reason" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "incentive_targets" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"partner_type" text DEFAULT 'ddp' NOT NULL,
	"month" integer NOT NULL,
	"year" integer NOT NULL,
	"target_installations" integer DEFAULT 5 NOT NULL,
	"target_capacity_kw" integer DEFAULT 15 NOT NULL,
	"achieved_installations" integer DEFAULT 0 NOT NULL,
	"achieved_capacity_kw" integer DEFAULT 0 NOT NULL,
	"bonus_amount" integer DEFAULT 0,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "leaderboard" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"partner_type" text DEFAULT 'ddp' NOT NULL,
	"period" text NOT NULL,
	"month" integer,
	"quarter" integer,
	"year" integer NOT NULL,
	"total_installations" integer DEFAULT 0 NOT NULL,
	"total_capacity_kw" integer DEFAULT 0 NOT NULL,
	"total_commission" integer DEFAULT 0 NOT NULL,
	"total_referrals" integer DEFAULT 0 NOT NULL,
	"rank" integer NOT NULL,
	"badge" text,
	"points" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "loan_disbursements" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar,
	"bank_loan_approval_id" varchar,
	"customer_name" text NOT NULL,
	"bank_name" text NOT NULL,
	"bank_branch" text,
	"disbursement_date" timestamp NOT NULL,
	"disbursement_time" text,
	"disbursed_amount" numeric(12, 2) NOT NULL,
	"transaction_reference" text,
	"divyanshi_bank_account" text,
	"status" text DEFAULT 'received',
	"remarks" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "meter_installation_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" text NOT NULL,
	"customer_id" varchar NOT NULL,
	"completion_report_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"site_address" text NOT NULL,
	"district" text,
	"state" text,
	"pincode" text,
	"installed_capacity" text,
	"panel_type" text,
	"inverter_type" text,
	"number_of_panels" integer,
	"old_meter_number" text,
	"old_meter_reading" text,
	"new_meter_number" text,
	"new_meter_type" text,
	"new_meter_make" text,
	"new_meter_model" text,
	"meter_serial_number" text,
	"meter_installation_date" timestamp,
	"initial_meter_reading" text,
	"ct_ratio" text,
	"discom_name" text,
	"discom_division" text,
	"consumer_number" text,
	"sanctioned_load" text,
	"connection_type" text,
	"supply_voltage" text,
	"grid_connection_date" timestamp,
	"synchronization_date" timestamp,
	"discom_rep_name" text,
	"discom_rep_designation" text,
	"discom_rep_phone" text,
	"discom_rep_employee_id" text,
	"dc_capacity" text,
	"ac_capacity" text,
	"dc_ac_ratio" text,
	"tilt_angle" text,
	"azimuth_angle" text,
	"array_configuration" text,
	"earthing_completed" boolean DEFAULT false,
	"lightning_arrester_installed" boolean DEFAULT false,
	"acdb_installed" boolean DEFAULT false,
	"dcdb_installed" boolean DEFAULT false,
	"mcb_rating" text,
	"spd_installed" boolean DEFAULT false,
	"grid_sync_test_passed" boolean DEFAULT false,
	"anti_islanding_test_passed" boolean DEFAULT false,
	"power_quality_test_passed" boolean DEFAULT false,
	"export_limit_set" boolean DEFAULT false,
	"export_limit_value" text,
	"meter_photos" text[],
	"connection_photos" text[],
	"test_report_photos" text[],
	"discom_certificate_url" text,
	"net_metering_agreement_url" text,
	"status" text DEFAULT 'pending',
	"discom_approval_status" text DEFAULT 'pending',
	"discom_approval_date" timestamp,
	"rejection_reason" text,
	"expected_generation" text,
	"warranty_period" text,
	"maintenance_schedule" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "meter_installation_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "milestones" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"milestone" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"completed_at" timestamp,
	"notes" text,
	"internal_notes" text,
	"visible_to_customer" boolean DEFAULT true,
	"updated_by_role" text,
	"updated_by_id" varchar,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "news_posts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"summary" text NOT NULL,
	"content" text NOT NULL,
	"category" text DEFAULT 'news' NOT NULL,
	"image_url" text,
	"author_id" varchar,
	"is_published" text DEFAULT 'false',
	"published_at" timestamp,
	"tags" text[],
	"view_count" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "news_posts_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "notification_templates" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"trigger" text NOT NULL,
	"trigger_value" text,
	"channel" text NOT NULL,
	"subject" text,
	"template" text NOT NULL,
	"is_active" text DEFAULT 'true',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"customer_id" varchar,
	"type" text NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"is_read" text DEFAULT 'false',
	"channel" text DEFAULT 'in_app',
	"sent_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "order_items" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" varchar NOT NULL,
	"product_id" varchar,
	"product_name" text NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"unit_price" integer NOT NULL,
	"total_price" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_number" text NOT NULL,
	"customer_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_email" text,
	"customer_address" text,
	"total_amount" integer NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"razorpay_order_id" text,
	"ddp_id" varchar,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "orders_order_number_unique" UNIQUE("order_number")
);
--> statement-breakpoint
CREATE TABLE "panel_models" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"brand" text NOT NULL,
	"type" text DEFAULT 'dcr' NOT NULL,
	"capacity_watt" integer NOT NULL,
	"efficiency" text,
	"warranty" text,
	"price_per_watt" integer,
	"dimensions" text,
	"weight" text,
	"technology" text,
	"features" text[],
	"image_url" text,
	"specifications" text,
	"is_active" text DEFAULT 'active',
	"sort_order" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "partner_of_month" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"month" integer NOT NULL,
	"year" integer NOT NULL,
	"achievement" text NOT NULL,
	"customers_count" integer DEFAULT 0,
	"total_commission" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "password_reset_otps" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"phone" text NOT NULL,
	"otp" text NOT NULL,
	"reset_token" text,
	"expires_at" timestamp NOT NULL,
	"used" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" varchar NOT NULL,
	"razorpay_payment_id" text,
	"razorpay_order_id" text,
	"razorpay_signature" text,
	"amount" integer NOT NULL,
	"currency" text DEFAULT 'INR',
	"method" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"failure_reason" text,
	"paid_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "payouts" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"commission_id" varchar,
	"amount" integer NOT NULL,
	"razorpay_payout_id" text,
	"razorpay_status" text,
	"mode" text DEFAULT 'IMPS',
	"utr" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"failure_reason" text,
	"processed_at" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "performance_metrics" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"partner_id" varchar NOT NULL,
	"partner_type" text DEFAULT 'ddp' NOT NULL,
	"month" integer NOT NULL,
	"year" integer NOT NULL,
	"total_installations" integer DEFAULT 0 NOT NULL,
	"total_capacity_kw" integer DEFAULT 0 NOT NULL,
	"dcr_installations" integer DEFAULT 0 NOT NULL,
	"non_dcr_installations" integer DEFAULT 0 NOT NULL,
	"inverters_sold" integer DEFAULT 0 NOT NULL,
	"total_commission_earned" integer DEFAULT 0 NOT NULL,
	"installation_commission" integer DEFAULT 0 NOT NULL,
	"inverter_commission" integer DEFAULT 0 NOT NULL,
	"bonus_earned" integer DEFAULT 0 NOT NULL,
	"rank" integer,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "portal_submission_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" text NOT NULL,
	"customer_id" varchar NOT NULL,
	"meter_installation_report_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"customer_email" text,
	"site_address" text,
	"district" text,
	"state" text,
	"pincode" text,
	"portal_registration_id" text,
	"portal_application_number" text,
	"discom_name" text,
	"consumer_number" text,
	"installed_capacity" text,
	"panel_type" text,
	"inverter_capacity" text,
	"grid_connection_date" timestamp,
	"net_meter_number" text,
	"submission_date" timestamp,
	"completion_certificate_number" text,
	"completion_certificate_date" timestamp,
	"completion_certificate_url" text,
	"meter_photo_url" text,
	"installation_photo_url" text,
	"site_photo_url" text,
	"net_metering_agreement_url" text,
	"bank_details_proof_url" text,
	"aadhar_card_url" text,
	"electricity_bill_url" text,
	"portal_acknowledgment_number" text,
	"portal_acknowledgment_date" timestamp,
	"portal_acknowledgment_url" text,
	"subsidy_scheme" text DEFAULT 'pm_surya_ghar',
	"central_subsidy_amount" integer,
	"state_subsidy_amount" integer,
	"total_subsidy_claimed" integer,
	"subsidy_approved_amount" integer,
	"subsidy_rejection_reason" text,
	"beneficiary_name" text,
	"beneficiary_account_number" text,
	"beneficiary_ifsc" text,
	"beneficiary_bank_name" text,
	"disbursement_status" text DEFAULT 'pending',
	"disbursement_reference_number" text,
	"disbursement_date" timestamp,
	"disbursement_amount" integer,
	"disbursement_remarks" text,
	"document_verification_status" text DEFAULT 'pending',
	"document_verification_date" timestamp,
	"document_verification_remarks" text,
	"physical_verification_required" boolean DEFAULT true,
	"physical_verification_date" timestamp,
	"physical_verification_officer" text,
	"physical_verification_status" text DEFAULT 'pending',
	"physical_verification_remarks" text,
	"status" text DEFAULT 'pending',
	"expected_disbursement_date" timestamp,
	"actual_processing_days" integer,
	"rejection_reason" text,
	"last_follow_up_date" timestamp,
	"next_follow_up_date" timestamp,
	"follow_up_remarks" text,
	"portal_helpline_ticket" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "portal_submission_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"category" text NOT NULL,
	"price" integer NOT NULL,
	"booking_amount" integer,
	"image_url" text,
	"is_active" text DEFAULT 'active',
	"stock" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "referrals" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"referrer_id" varchar NOT NULL,
	"referred_type" text NOT NULL,
	"referred_customer_id" varchar,
	"referred_partner_id" varchar,
	"referral_code" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"reward_amount" integer,
	"reward_status" text DEFAULT 'pending',
	"conversion_date" timestamp,
	"expires_at" timestamp,
	"notes" text,
	"partner_installation_count" integer DEFAULT 0,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "remaining_payment_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" varchar,
	"customer_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"customer_email" text,
	"site_address" text,
	"district" text,
	"state" text,
	"pincode" text,
	"installed_capacity" text,
	"panel_type" text,
	"consumer_number" text,
	"discom_name" text,
	"portal_submission_report_id" varchar,
	"portal_application_number" text,
	"completion_date" timestamp,
	"subsidy_received_date" timestamp,
	"subsidy_amount" integer,
	"total_system_cost" integer,
	"advance_payment_received" integer,
	"advance_payment_date" timestamp,
	"subsidy_adjusted" integer,
	"remaining_payment_amount" integer,
	"remaining_payment_due_date" timestamp,
	"payment_reminder_sent" boolean DEFAULT false,
	"reminder_sent_date" timestamp,
	"reminder_count" integer DEFAULT 0,
	"payment_mode" text,
	"payment_reference_number" text,
	"payment_received_date" timestamp,
	"payment_received_amount" integer,
	"payment_receipt_number" text,
	"payment_receipt_url" text,
	"is_partial_payment" boolean DEFAULT false,
	"partial_payments" text,
	"total_received_till_date" integer,
	"balance_amount" integer,
	"status" text DEFAULT 'pending',
	"days_overdue" integer DEFAULT 0,
	"last_follow_up_date" timestamp,
	"next_follow_up_date" timestamp,
	"follow_up_remarks" text,
	"commission_held" boolean DEFAULT true,
	"commission_release_date" timestamp,
	"ddp_commission_amount" integer,
	"bdp_commission_amount" integer,
	"customer_feedback" text,
	"escalation_required" boolean DEFAULT false,
	"escalation_reason" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "remaining_payment_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "service_requests" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"request_number" text NOT NULL,
	"customer_id" varchar NOT NULL,
	"issue_type" text NOT NULL,
	"issue_title" text NOT NULL,
	"issue_description" text NOT NULL,
	"urgency" text DEFAULT 'normal',
	"customer_name" text NOT NULL,
	"customer_phone" text NOT NULL,
	"customer_address" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"assigned_vendor_id" varchar,
	"assigned_at" timestamp,
	"assigned_by" varchar,
	"scheduled_visit_date" timestamp,
	"actual_visit_date" timestamp,
	"vendor_notes" text,
	"vendor_selfie_with_customer" text,
	"resolution_notes" text,
	"resolved_at" timestamp,
	"resolution_photos" text[],
	"customer_feedback_rating" integer,
	"customer_feedback_text" text,
	"feedback_submitted_at" timestamp,
	"admin_notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "service_requests_request_number_unique" UNIQUE("request_number")
);
--> statement-breakpoint
CREATE TABLE "site_execution_completion_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" text NOT NULL,
	"execution_order_id" varchar NOT NULL,
	"vendor_id" varchar,
	"customer_name" text NOT NULL,
	"site_address" text NOT NULL,
	"completion_date" timestamp NOT NULL,
	"work_summary" text,
	"scope_completed_as" text,
	"deviations_notes" text,
	"materials_used" text,
	"extra_materials_used" text,
	"total_work_hours" integer,
	"crew_size" integer,
	"panels_installed" integer,
	"inverter_installed" text,
	"wiring_completed" boolean DEFAULT false,
	"earthing_completed" boolean DEFAULT false,
	"meter_connected" boolean DEFAULT false,
	"grid_sync_completed" boolean DEFAULT false,
	"before_photos" text[],
	"during_photos" text[],
	"after_photos" text[],
	"panel_photos" text[],
	"inverter_photos" text[],
	"wiring_photos" text[],
	"meter_photos" text[],
	"meter_reading" text,
	"generation_test_passed" boolean DEFAULT false,
	"test_reading_kw" text,
	"quality_checklist_completed" boolean DEFAULT false,
	"safety_checklist_completed" boolean DEFAULT false,
	"cleanup_completed" boolean DEFAULT false,
	"customer_briefing_done" boolean DEFAULT false,
	"customer_signature" text,
	"customer_name_signed" text,
	"customer_phone" text,
	"customer_feedback" text,
	"customer_rating" integer,
	"vendor_rep_name" text,
	"vendor_rep_phone" text,
	"vendor_signature" text,
	"status" text DEFAULT 'draft',
	"submitted_at" timestamp,
	"reviewed_at" timestamp,
	"reviewed_by" varchar,
	"review_notes" text,
	"rejection_reason" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "site_execution_completion_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "site_execution_orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_number" text NOT NULL,
	"customer_id" varchar,
	"vendor_id" varchar,
	"purchase_order_id" varchar,
	"delivery_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"site_address" text NOT NULL,
	"district" text,
	"state" text,
	"pincode" text,
	"vendor_name" text,
	"vendor_contact_person" text,
	"vendor_phone" text,
	"scheduled_start_date" timestamp NOT NULL,
	"scheduled_end_date" timestamp,
	"actual_start_date" timestamp,
	"actual_end_date" timestamp,
	"estimated_duration" integer,
	"crew_lead_name" text,
	"crew_lead_phone" text,
	"crew_size" integer,
	"crew_members" text[],
	"scope_of_work" text,
	"work_description" text,
	"panel_type" text,
	"panel_capacity" text,
	"inverter_type" text,
	"number_of_panels" integer,
	"site_installation_rate" text DEFAULT '2.5',
	"required_materials" text[],
	"required_tools" text[],
	"special_instructions" text,
	"safety_checklist_completed" boolean DEFAULT false,
	"safety_notes" text,
	"permits_required" text[],
	"permits_obtained" boolean DEFAULT false,
	"status" text DEFAULT 'draft',
	"progress_percentage" integer DEFAULT 0,
	"progress_notes" text,
	"quality_check_completed" boolean DEFAULT false,
	"quality_check_notes" text,
	"quality_check_date" timestamp,
	"quality_checked_by" text,
	"completion_certificate" text,
	"completion_photos" text[],
	"customer_signoff" text,
	"customer_signoff_date" timestamp,
	"customer_feedback" text,
	"customer_rating" integer,
	"hold_reason" text,
	"cancel_reason" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "site_execution_orders_order_number_unique" UNIQUE("order_number")
);
--> statement-breakpoint
CREATE TABLE "site_expenses" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"site_id" text NOT NULL,
	"customer_payment_received" numeric(12, 2) DEFAULT '0',
	"solar_panels_cost" numeric(12, 2) DEFAULT '0',
	"inverter_cost" numeric(12, 2) DEFAULT '0',
	"electrical_cost" numeric(12, 2) DEFAULT '0',
	"civil_work_cost" numeric(12, 2) DEFAULT '0',
	"electrician_cost" numeric(12, 2) DEFAULT '0',
	"meter_cost" numeric(12, 2) DEFAULT '0',
	"meter_installation_cost" numeric(12, 2) DEFAULT '0',
	"logistic_cost" numeric(12, 2) DEFAULT '0',
	"bank_loan_approval_cost" numeric(12, 2) DEFAULT '0',
	"discom_approval_cost" numeric(12, 2) DEFAULT '0',
	"bdp_commission" numeric(12, 2) DEFAULT '0',
	"ddp_commission" numeric(12, 2) DEFAULT '0',
	"referral_payment" numeric(12, 2) DEFAULT '0',
	"incentive_payment" numeric(12, 2) DEFAULT '0',
	"miscellaneous_expense" numeric(12, 2) DEFAULT '0',
	"miscellaneous_notes" text,
	"total_expenses" numeric(12, 2) DEFAULT '0',
	"profit" numeric(12, 2) DEFAULT '0',
	"profit_margin" numeric(5, 2) DEFAULT '0',
	"status" text DEFAULT 'pending' NOT NULL,
	"approved_by" varchar,
	"approved_at" timestamp,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "site_expenses_site_id_unique" UNIQUE("site_id")
);
--> statement-breakpoint
CREATE TABLE "site_surveys" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"survey_number" text NOT NULL,
	"customer_id" varchar NOT NULL,
	"loan_submission_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"site_address" text NOT NULL,
	"district" text,
	"state" text,
	"pincode" text,
	"scheduled_date" timestamp NOT NULL,
	"actual_date" timestamp,
	"survey_time" text,
	"bank_name" text,
	"bank_branch" text,
	"bank_staff_name" text,
	"bank_staff_designation" text,
	"bank_staff_phone" text,
	"bank_survey_completed" boolean DEFAULT false,
	"bank_survey_date" timestamp,
	"bank_survey_notes" text,
	"bank_approval_status" text DEFAULT 'pending',
	"discom_name" text,
	"discom_division" text,
	"discom_rep_name" text,
	"discom_rep_designation" text,
	"discom_rep_phone" text,
	"discom_survey_completed" boolean DEFAULT false,
	"discom_survey_date" timestamp,
	"discom_survey_notes" text,
	"discom_approval_status" text DEFAULT 'pending',
	"roof_condition" text,
	"roof_type" text,
	"roof_area" integer,
	"shadow_analysis" text,
	"structural_feasibility" text,
	"electrical_feasibility" text,
	"existing_meter_type" text,
	"meter_location" text,
	"sanctioned_load" text,
	"proposed_capacity" text,
	"grid_connection_distance" text,
	"roof_photos" text[],
	"meter_photos" text[],
	"site_photos" text[],
	"status" text DEFAULT 'scheduled',
	"overall_recommendation" text,
	"recommended_capacity" text,
	"special_conditions" text,
	"rejection_reason" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "site_surveys_survey_number_unique" UNIQUE("survey_number")
);
--> statement-breakpoint
CREATE TABLE "subsidy_application_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" varchar,
	"customer_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"customer_email" text,
	"site_address" text,
	"district" text,
	"state" text,
	"pincode" text,
	"installed_capacity" text,
	"panel_type" text,
	"consumer_number" text,
	"discom_name" text,
	"portal_registration_id" text,
	"portal_application_number" text,
	"completion_certificate_number" text,
	"completion_certificate_date" timestamp,
	"net_meter_number" text,
	"grid_connection_date" timestamp,
	"application_date" timestamp,
	"subsidy_scheme" text DEFAULT 'pm_surya_ghar',
	"central_subsidy_amount" integer,
	"state_subsidy_amount" integer,
	"total_subsidy_applied" integer,
	"beneficiary_name" text,
	"beneficiary_account_number" text,
	"beneficiary_ifsc" text,
	"beneficiary_bank_name" text,
	"beneficiary_bank_branch" text,
	"completion_certificate_url" text,
	"net_metering_agreement_url" text,
	"bank_passbook_url" text,
	"aadhar_card_url" text,
	"electricity_bill_url" text,
	"installation_photos_url" text,
	"application_acknowledgment_number" text,
	"application_acknowledgment_date" timestamp,
	"document_verification_status" text DEFAULT 'pending',
	"document_verification_date" timestamp,
	"document_verification_remarks" text,
	"status" text DEFAULT 'pending',
	"rejection_reason" text,
	"last_follow_up_date" timestamp,
	"next_follow_up_date" timestamp,
	"follow_up_remarks" text,
	"portal_helpline_ticket" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "subsidy_application_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "subsidy_disbursement_reports" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"report_number" varchar,
	"customer_id" varchar,
	"customer_name" text NOT NULL,
	"customer_phone" text,
	"customer_email" text,
	"site_address" text,
	"district" text,
	"state" text,
	"pincode" text,
	"installed_capacity" text,
	"panel_type" text,
	"consumer_number" text,
	"subsidy_application_report_id" varchar,
	"portal_application_number" text,
	"subsidy_scheme" text,
	"central_subsidy_approved" integer,
	"state_subsidy_approved" integer,
	"total_subsidy_approved" integer,
	"disbursement_status" text DEFAULT 'pending',
	"disbursement_reference_number" text,
	"disbursement_date" timestamp,
	"disbursement_amount" integer,
	"disbursement_mode" text,
	"beneficiary_name" text,
	"beneficiary_account_number" text,
	"beneficiary_ifsc" text,
	"beneficiary_bank_name" text,
	"disbursement_verified" boolean DEFAULT false,
	"verification_date" timestamp,
	"verification_remarks" text,
	"bank_statement_url" text,
	"commission_release_triggered" boolean DEFAULT false,
	"commission_release_date" timestamp,
	"ddp_commission_released" integer,
	"bdp_commission_released" integer,
	"cp_commission_released" integer,
	"status" text DEFAULT 'pending',
	"expected_disbursement_date" timestamp,
	"actual_processing_days" integer,
	"last_follow_up_date" timestamp,
	"next_follow_up_date" timestamp,
	"follow_up_remarks" text,
	"remarks" text,
	"created_by" varchar,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "subsidy_disbursement_reports_report_number_unique" UNIQUE("report_number")
);
--> statement-breakpoint
CREATE TABLE "user_preferences" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" varchar NOT NULL,
	"tutorial_completed" text DEFAULT 'false',
	"dashboard_layout" text,
	"email_notifications" text DEFAULT 'true',
	"sms_notifications" text DEFAULT 'true',
	"whatsapp_notifications" text DEFAULT 'true',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "user_preferences_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"role" text DEFAULT 'ddp' NOT NULL,
	"district" text,
	"state" text,
	"address" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"parent_id" varchar,
	"referral_code" text,
	"linked_customer_id" varchar,
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_referral_code_unique" UNIQUE("referral_code")
);
--> statement-breakpoint
CREATE TABLE "vendor_payments" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar NOT NULL,
	"vendor_id" varchar NOT NULL,
	"assignment_id" varchar,
	"vendor_type" text NOT NULL,
	"milestone" text NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"description" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"milestone_completed_at" timestamp,
	"milestone_completed_by" varchar,
	"payout_approved_by" varchar,
	"payout_approved_at" timestamp,
	"razorpay_payout_id" text,
	"razorpay_payout_status" text,
	"paid_at" timestamp,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vendor_purchase_orders" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" varchar,
	"vendor_id" varchar,
	"loan_disbursement_id" varchar,
	"po_number" text NOT NULL,
	"customer_name" text NOT NULL,
	"vendor_name" text NOT NULL,
	"order_date" timestamp NOT NULL,
	"expected_delivery_date" timestamp,
	"panel_type" text,
	"panel_capacity" text,
	"inverter_type" text,
	"quantity" integer DEFAULT 1,
	"order_amount" numeric(12, 2) NOT NULL,
	"gst_amount" numeric(12, 2),
	"total_amount" numeric(12, 2) NOT NULL,
	"advance_amount" numeric(12, 2),
	"advance_date" timestamp,
	"advance_reference" text,
	"balance_amount" numeric(12, 2),
	"balance_paid_date" timestamp,
	"balance_reference" text,
	"payment_status" text DEFAULT 'pending',
	"order_status" text DEFAULT 'draft',
	"delivery_date" timestamp,
	"delivery_notes" text,
	"remarks" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "vendors" (
	"id" varchar PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vendor_type" text DEFAULT 'solar_installation' NOT NULL,
	"vendor_code" text,
	"name" text NOT NULL,
	"father_name" text,
	"date_of_birth" text,
	"phone" text NOT NULL,
	"alternate_phone" text,
	"email" text,
	"company_name" text,
	"company_type" text,
	"state" text NOT NULL,
	"district" text NOT NULL,
	"address" text NOT NULL,
	"pincode" text NOT NULL,
	"services" text[],
	"experience_years" text,
	"total_installations" integer,
	"previous_companies" text,
	"projects_completed" text,
	"specializations" text[],
	"team_size" integer,
	"supervisor_count" integer,
	"helper_count" integer,
	"equipment_owned" text[],
	"has_transportation" boolean DEFAULT false,
	"vehicle_details" text,
	"certifications" text[],
	"training_details" text,
	"aadhar_number" text,
	"pan_number" text,
	"gst_number" text,
	"bank_account_name" text,
	"bank_account_number" text,
	"bank_ifsc" text,
	"bank_name" text,
	"upi_id" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "vendors_vendor_code_unique" UNIQUE("vendor_code")
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"conversation_id" integer NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "bank_loan_approvals" ADD CONSTRAINT "bank_loan_approvals_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bank_loan_approvals" ADD CONSTRAINT "bank_loan_approvals_bank_loan_submission_id_bank_loan_submissions_id_fk" FOREIGN KEY ("bank_loan_submission_id") REFERENCES "public"."bank_loan_submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_file_submissions" ADD CONSTRAINT "customer_file_submissions_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_vendor_assignments" ADD CONSTRAINT "customer_vendor_assignments_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_vendor_assignments" ADD CONSTRAINT "customer_vendor_assignments_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_vendor_assignments" ADD CONSTRAINT "customer_vendor_assignments_assigned_by_users_id_fk" FOREIGN KEY ("assigned_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_deliveries" ADD CONSTRAINT "goods_deliveries_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_deliveries" ADD CONSTRAINT "goods_deliveries_purchase_order_id_vendor_purchase_orders_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "public"."vendor_purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goods_deliveries" ADD CONSTRAINT "goods_deliveries_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loan_disbursements" ADD CONSTRAINT "loan_disbursements_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "loan_disbursements" ADD CONSTRAINT "loan_disbursements_bank_loan_approval_id_bank_loan_approvals_id_fk" FOREIGN KEY ("bank_loan_approval_id") REFERENCES "public"."bank_loan_approvals"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meter_installation_reports" ADD CONSTRAINT "meter_installation_reports_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meter_installation_reports" ADD CONSTRAINT "meter_installation_reports_completion_report_id_site_execution_completion_reports_id_fk" FOREIGN KEY ("completion_report_id") REFERENCES "public"."site_execution_completion_reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meter_installation_reports" ADD CONSTRAINT "meter_installation_reports_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portal_submission_reports" ADD CONSTRAINT "portal_submission_reports_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portal_submission_reports" ADD CONSTRAINT "portal_submission_reports_meter_installation_report_id_meter_installation_reports_id_fk" FOREIGN KEY ("meter_installation_report_id") REFERENCES "public"."meter_installation_reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portal_submission_reports" ADD CONSTRAINT "portal_submission_reports_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remaining_payment_reports" ADD CONSTRAINT "remaining_payment_reports_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remaining_payment_reports" ADD CONSTRAINT "remaining_payment_reports_portal_submission_report_id_portal_submission_reports_id_fk" FOREIGN KEY ("portal_submission_report_id") REFERENCES "public"."portal_submission_reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remaining_payment_reports" ADD CONSTRAINT "remaining_payment_reports_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_completion_reports" ADD CONSTRAINT "site_execution_completion_reports_execution_order_id_site_execution_orders_id_fk" FOREIGN KEY ("execution_order_id") REFERENCES "public"."site_execution_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_completion_reports" ADD CONSTRAINT "site_execution_completion_reports_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_orders" ADD CONSTRAINT "site_execution_orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_orders" ADD CONSTRAINT "site_execution_orders_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_orders" ADD CONSTRAINT "site_execution_orders_purchase_order_id_vendor_purchase_orders_id_fk" FOREIGN KEY ("purchase_order_id") REFERENCES "public"."vendor_purchase_orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_execution_orders" ADD CONSTRAINT "site_execution_orders_delivery_id_goods_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "public"."goods_deliveries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_surveys" ADD CONSTRAINT "site_surveys_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_surveys" ADD CONSTRAINT "site_surveys_loan_submission_id_bank_loan_submissions_id_fk" FOREIGN KEY ("loan_submission_id") REFERENCES "public"."bank_loan_submissions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subsidy_application_reports" ADD CONSTRAINT "subsidy_application_reports_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subsidy_application_reports" ADD CONSTRAINT "subsidy_application_reports_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subsidy_disbursement_reports" ADD CONSTRAINT "subsidy_disbursement_reports_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subsidy_disbursement_reports" ADD CONSTRAINT "subsidy_disbursement_reports_subsidy_application_report_id_subsidy_application_reports_id_fk" FOREIGN KEY ("subsidy_application_report_id") REFERENCES "public"."subsidy_application_reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subsidy_disbursement_reports" ADD CONSTRAINT "subsidy_disbursement_reports_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD CONSTRAINT "vendor_payments_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD CONSTRAINT "vendor_payments_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD CONSTRAINT "vendor_payments_assignment_id_customer_vendor_assignments_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."customer_vendor_assignments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD CONSTRAINT "vendor_payments_milestone_completed_by_users_id_fk" FOREIGN KEY ("milestone_completed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_payments" ADD CONSTRAINT "vendor_payments_payout_approved_by_users_id_fk" FOREIGN KEY ("payout_approved_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_purchase_orders" ADD CONSTRAINT "vendor_purchase_orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_purchase_orders" ADD CONSTRAINT "vendor_purchase_orders_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_purchase_orders" ADD CONSTRAINT "vendor_purchase_orders_loan_disbursement_id_loan_disbursements_id_fk" FOREIGN KEY ("loan_disbursement_id") REFERENCES "public"."loan_disbursements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;